apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-service
  description: Welcome, Backstage!
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guests
